/* SciFi — Data Layer with actual 33 clubs across 10 departments */

const DEPARTMENTS = [
    { id: 'biotech-bsc', name: 'BioTech (BSc)', icon: 'fas fa-dna', color: '#27ae60', bgColor: '#e8f8f0' },
    { id: 'pharmacy', name: 'School of Pharmacy', icon: 'fas fa-pills', color: '#2ecc71', bgColor: '#eafaf1' },
    { id: 'legal', name: 'School of Legal Studies', icon: 'fas fa-gavel', color: '#8e44ad', bgColor: '#f5eef8' },
    { id: 'forensic', name: 'School of Forensic Science', icon: 'fas fa-fingerprint', color: '#c0392b', bgColor: '#fdedec' },
    { id: 'cse', name: 'School of CSE', icon: 'fas fa-laptop-code', color: '#2980b9', bgColor: '#ebf5fb' },
    { id: 'computing', name: 'School of Computing', icon: 'fas fa-server', color: '#3498db', bgColor: '#eaf2f8' },
    { id: 'management', name: 'School of Management', icon: 'fas fa-briefcase', color: '#e67e22', bgColor: '#fef5e7' },
    { id: 'engineering', name: 'School of Engineering', icon: 'fas fa-cogs', color: '#e74c3c', bgColor: '#fdedec' },
    { id: 'biotech-btech', name: 'BioTech (BTech)', icon: 'fas fa-atom', color: '#16a085', bgColor: '#e8f8f5' },
    { id: 'applied-science', name: 'School of Applied Science', icon: 'fas fa-flask', color: '#f39c12', bgColor: '#fef9e7' }
];

const TEAMS = [
    { id: 'velocity', name: 'Velocity Formula Racing', tagline: 'Speed. Precision. Engineering.', icon: 'fas fa-car', color: '#c21807', bgColor: '#fbe9e7', shortDesc: 'Designing and racing formula-style cars in international competitions.', about: 'Velocity Formula Racing is the premier motorsport team that designs, builds, and races a single-seat formula-style race car. The team competes in Formula SAE events globally, pushing the boundaries of automotive engineering, aerodynamics, and performance.', achievements: [{ title: 'FSAE India — Overall 3rd', desc: 'Secured 3rd place overall at Formula SAE India 2024.' }, { title: 'Best Design Award', desc: 'Won the Best Engineering Design award at FSAE Australasia.' }], projects: [{ title: 'Electric Powertrain', desc: 'Developing a high-performance 80kW electric powertrain.', tag: 'Active' }, { title: 'Aerodynamics CFD', desc: 'Advanced CFD analysis for optimized downforce package.', tag: 'Active' }], leads: [{ name: 'Team Lead', role: 'Captain', email: '#', linkedin: '#' }] },
    { id: 'rover', name: 'Team Rover', tagline: 'Exploring the Unexplored.', icon: 'fas fa-shuttle-space', color: '#e67e22', bgColor: '#fff5eb', shortDesc: 'Building autonomous rovers for interplanetary surface exploration.', about: 'Team Rover focuses on designing and building advanced planetary rovers capable of traversing rugged terrain, performing scientific experiments, and autonomous navigation, competing in international rover challenges.', achievements: [{ title: 'University Rover Challenge — Top 10', desc: 'Ranked in the top 10 globally at URC 2024.' }, { title: 'Best Science Payload', desc: 'Won best science system design award.' }], projects: [{ title: 'Life Detection System', desc: 'Developing a Raman spectroscopy-based life detection unit.', tag: 'Active' }, { title: 'Autonomous Mapping', desc: 'SLAM-based mapping in GNSS-denied environments.', tag: 'Research' }], leads: [{ name: 'Lead Engineer', role: 'Captain', email: '#', linkedin: '#' }] },
    { id: 'hyperloop', name: 'Team Hyperloop', tagline: 'The Future of Transport.', icon: 'fas fa-train', color: '#3498db', bgColor: '#ebf5fb', shortDesc: 'Developing high-speed hyperloop pod prototypes for rapid transit.', about: 'Team Hyperloop is dedicated to making the fifth mode of transport a reality. We design and build pod prototypes that utilize magnetic levitation and vacuum-tube environments for ultra-high-speed travel.', achievements: [{ title: 'Global Hyperloop Competition Finalist', desc: 'Qualified as one of the top 15 teams worldwide.' }, { title: 'Innovation in Levitation', desc: 'Best magnetic levitation design award.' }], projects: [{ title: 'MagLev Chassis', desc: 'Optimizing magnetic levitation stability at 400km/h.', tag: 'Active' }, { title: 'Vacuum Braking', desc: 'Fail-safe braking systems for vacuum environments.', tag: 'Active' }], leads: [{ name: 'Project Head', role: 'Lead', email: '#', linkedin: '#' }] }
];

const CLUBS = [
    { id: 'bio-innovation', departmentId: 'biotech-bsc', name: 'Bio Innovation Club', advisor: 'Dr. Priti Krishna Majhi', icon: 'fas fa-dna', color: '#27ae60', bgColor: '#e8f8f0', shortDesc: 'Fostering innovation in biological sciences through research and experiments.', about: 'The Bio Innovation Club is a platform for students passionate about biological sciences to explore innovative ideas, conduct research experiments, and develop biotechnological solutions. Members engage in hands-on lab work, seminars, and interdisciplinary projects that bridge biology with technology.', achievements: [{ title: 'Best Research Poster Award', desc: 'Won best poster at the National Biotech Symposium.' }, { title: 'Bio Innovation Hackathon', desc: 'Organized a successful campus-wide bio-hackathon with 100+ participants.' }], projects: [{ title: 'Bioplastic Development', desc: 'Developing biodegradable plastic alternatives from biological waste.', tag: 'Active' }, { title: 'Enzyme Optimization', desc: 'Optimizing industrial enzymes using directed evolution techniques.', tag: 'Research' }], leads: [{ name: 'Dr. Priti Krishna Majhi', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'bio-4-life', departmentId: 'biotech-bsc', name: 'Bio 4 Life', advisor: 'Dr. Priti Krishna Majhi', icon: 'fas fa-leaf', color: '#2ecc71', bgColor: '#eafaf1', shortDesc: 'Promoting awareness about biology and its impact on everyday life.', about: 'Bio 4 Life is dedicated to spreading awareness about how biology touches every aspect of our daily lives. The club organizes awareness campaigns, workshops, and community outreach programs focused on health, environment, and sustainable living.', achievements: [{ title: 'Campus Green Initiative', desc: 'Led a campus-wide sustainability drive reducing plastic use by 40%.' }, { title: 'Health Awareness Week', desc: 'Organized health awareness week reaching 500+ students.' }], projects: [{ title: 'Campus Biodiversity Survey', desc: 'Documenting and cataloging campus flora and fauna.', tag: 'Active' }, { title: 'Organic Garden', desc: 'Maintaining an organic vegetable garden on campus.', tag: 'Active' }], leads: [{ name: 'Dr. Priti Krishna Majhi', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'herbal-club', departmentId: 'pharmacy', name: 'Herbal Club', advisor: 'Dr. Pradeep Singh', icon: 'fas fa-seedling', color: '#27ae60', bgColor: '#e8f8f0', shortDesc: 'Exploring traditional herbal medicine and pharmacognosy.', about: 'The Herbal Club explores the vast world of traditional herbal medicine, pharmacognosy, and natural product chemistry. Members study medicinal plants, prepare herbal formulations, and research the scientific basis behind traditional remedies.', achievements: [{ title: 'Herbal Garden Establishment', desc: 'Established a medicinal plant garden with 50+ species.' }, { title: 'Herbal Medicine Seminar', desc: 'Conducted a seminar on evidence-based herbal medicine.' }], projects: [{ title: 'Medicinal Plant Database', desc: 'Creating a digital database of medicinal plants with pharmacological properties.', tag: 'Active' }, { title: 'Herbal Formulations', desc: 'Developing standardized herbal formulations for common ailments.', tag: 'Research' }], leads: [{ name: 'Dr. Pradeep Singh', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'cosmetic-club', departmentId: 'pharmacy', name: 'Cosmetic Club', advisor: 'Dr. Shruti Srivastava', icon: 'fas fa-flask', color: '#e91e63', bgColor: '#fce4ec', shortDesc: 'Formulation and science behind cosmetics and personal care.', about: 'The Cosmetic Club dives into cosmetic science — from skincare formulations to personal care product development. Members learn about cosmeceuticals, skin biology, ingredient safety, and create their own formulations in the lab.', achievements: [{ title: 'Cosmetic Science Workshop', desc: 'Hosted hands-on workshops on natural cosmetic formulation.' }, { title: 'Product Innovation', desc: 'Developed 5 novel herbal cosmetic prototypes.' }], projects: [{ title: 'Natural Sunscreen', desc: 'Formulating herbal-based sunscreen with SPF validation.', tag: 'Active' }, { title: 'Cosmetic Safety Testing', desc: 'Establishing protocols for in-vitro cosmetic safety assessment.', tag: 'Research' }], leads: [{ name: 'Dr. Shruti Srivastava', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'discovery-club', departmentId: 'pharmacy', name: 'Discovery Club', advisor: 'Dr. Sanjesh Kumar', icon: 'fas fa-search', color: '#9b59b6', bgColor: '#f5eef8', shortDesc: 'Drug discovery, pharmaceutical research, and innovation.', about: 'The Discovery Club focuses on the exciting world of drug discovery and pharmaceutical innovation. Members explore the drug development pipeline, from target identification to clinical trials, through case studies, research projects, and industry interactions.', achievements: [{ title: 'Drug Discovery Symposium', desc: 'Organized an inter-college symposium on modern drug discovery.' }, { title: 'Research Publication', desc: 'Members co-authored research papers on novel drug targets.' }], projects: [{ title: 'Virtual Screening', desc: 'Using computational methods to screen potential drug candidates.', tag: 'Research' }, { title: 'Drug Repurposing', desc: 'Exploring existing drugs for new therapeutic applications.', tag: 'Active' }], leads: [{ name: 'Dr. Sanjesh Kumar', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'health-club', departmentId: 'pharmacy', name: 'Health Club', advisor: 'Dr. Sanjesh Kumar', icon: 'fas fa-heartbeat', color: '#e74c3c', bgColor: '#fdedec', shortDesc: 'Promoting health awareness and community wellness initiatives.', about: 'The Health Club is dedicated to promoting health literacy and wellness among students and the surrounding community. Through health camps, awareness drives, fitness programs, and expert talks, the club makes healthcare knowledge accessible to all.', achievements: [{ title: 'Blood Donation Drive', desc: 'Organized blood donation camps collecting 200+ units.' }, { title: 'Health Screening Camp', desc: 'Conducted free health screening camps for nearby villages.' }], projects: [{ title: 'Mental Health Campaign', desc: 'Campus-wide mental health awareness and support initiative.', tag: 'Active' }, { title: 'First Aid Training', desc: 'Regular first aid and CPR training workshops for students.', tag: 'Active' }], leads: [{ name: 'Dr. Sanjesh Kumar', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'moot-court-society', departmentId: 'legal', name: 'Moot Court Society', advisor: 'Mr. Ashish Shukla', icon: 'fas fa-gavel', color: '#8e44ad', bgColor: '#f5eef8', shortDesc: 'Practicing advocacy and legal argumentation through moot courts.', about: 'The Moot Court Society provides students with a platform to develop their advocacy, legal research, and argumentation skills. Members participate in intra and inter-college moot court competitions, preparing memorials and delivering oral arguments on contemporary legal issues.', achievements: [{ title: 'National Moot Court Finalist', desc: 'Reached finals at national-level moot court competition.' }, { title: 'Best Speaker Award', desc: 'Multiple members won best speaker awards at state competitions.' }], projects: [{ title: 'Moot Problem Bank', desc: 'Curating a comprehensive bank of moot problems and model memorials.', tag: 'Active' }, { title: 'Mock Trial Series', desc: 'Monthly mock trial sessions for skill development.', tag: 'Active' }], leads: [{ name: 'Mr. Ashish Shukla', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'legal-aid-cell', departmentId: 'legal', name: 'Legal Aid Cell', advisor: 'Mr. Raunak Tiwari', icon: 'fas fa-balance-scale', color: '#7d3c98', bgColor: '#f4ecf7', shortDesc: 'Providing free legal assistance and awareness to the community.', about: 'The Legal Aid Cell bridges the gap between legal knowledge and community access to justice. Students provide free legal assistance, organize legal awareness camps, and contribute to access-to-justice initiatives under faculty supervision.', achievements: [{ title: 'Community Legal Camp', desc: 'Conducted 10+ legal awareness camps in rural areas.' }, { title: 'Legal Literacy Drive', desc: 'Educated 1000+ individuals about their fundamental rights.' }], projects: [{ title: 'Legal Helpdesk', desc: 'Running a free legal consultation helpdesk for local community.', tag: 'Active' }, { title: 'Know Your Rights Booklet', desc: 'Publishing multilingual booklets on fundamental legal rights.', tag: 'Active' }], leads: [{ name: 'Mr. Raunak Tiwari', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'pro-bono-club', departmentId: 'legal', name: 'Pro Bono Club', advisor: 'Mr. Yashraj Singh Parihar', icon: 'fas fa-hands-helping', color: '#6c3483', bgColor: '#f2e6f9', shortDesc: 'Volunteering legal expertise for public interest and social justice.', about: 'The Pro Bono Club instills the spirit of giving back. Members volunteer their legal knowledge and skills for public interest causes, contribute to social justice research, and support NGOs and community organizations with legal compliance and advocacy.', achievements: [{ title: 'NGO Legal Support', desc: 'Provided legal documentation support to 5 local NGOs.' }, { title: 'Social Justice Workshop', desc: 'Organized workshops on constitutional rights and social justice.' }], projects: [{ title: 'Street Law Program', desc: 'Teaching basic legal concepts in local schools.', tag: 'Active' }, { title: 'Environmental Law Campaign', desc: 'Awareness campaign on environmental protection laws.', tag: 'Active' }], leads: [{ name: 'Mr. Yashraj Singh Parihar', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'crime-scene', departmentId: 'forensic', name: 'Crime Scene & Investigator', advisor: 'Dr. Prateek Singh', icon: 'fas fa-fingerprint', color: '#c0392b', bgColor: '#fdedec', shortDesc: 'Hands-on crime scene investigation and evidence analysis techniques.', about: 'The Crime Scene & Investigator club trains students in practical crime scene investigation (CSI) techniques. From evidence collection and fingerprint analysis to blood spatter interpretation and digital forensics, members gain hands-on experience in forensic methodology.', achievements: [{ title: 'Mock Crime Scene Competition', desc: 'Organized and won inter-college mock crime scene competitions.' }, { title: 'Forensic Workshop', desc: 'Conducted advanced forensic evidence analysis workshops.' }], projects: [{ title: 'Crime Scene Simulation Lab', desc: 'Setting up a mock crime scene simulation facility.', tag: 'Active' }, { title: 'Evidence Analysis Toolkit', desc: 'Developing a portable evidence collection and analysis kit.', tag: 'Research' }], leads: [{ name: 'Dr. Prateek Singh', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'moot-court-trials', departmentId: 'forensic', name: 'Moot Court & Trials Club', advisor: 'Dr. Prateek Singh', icon: 'fas fa-landmark', color: '#a93226', bgColor: '#f9e0de', shortDesc: 'Simulating courtroom trials with forensic evidence presentation.', about: 'The Moot Court & Trials Club combines forensic science with legal proceedings. Members simulate courtroom trials where forensic evidence plays a pivotal role, learning how to present scientific findings as expert witnesses and understanding courtroom procedures.', achievements: [{ title: 'Inter-College Trial Competition', desc: 'Won best forensic evidence presentation at mock trial competition.' }, { title: 'Expert Witness Training', desc: 'Trained 50+ students in expert witness testimony techniques.' }], projects: [{ title: 'Forensic Trial Database', desc: 'Compiling landmark cases where forensic evidence was pivotal.', tag: 'Active' }, { title: 'Trial Simulation Series', desc: 'Monthly courtroom trial simulations with forensic scenarios.', tag: 'Active' }], leads: [{ name: 'Dr. Prateek Singh', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'film-forensic', departmentId: 'forensic', name: 'Film Forensic Club', advisor: 'Dr. Prateek Singh', icon: 'fas fa-film', color: '#d35400', bgColor: '#fef5e7', shortDesc: 'Analyzing forensic science as portrayed in films and media.', about: 'The Film Forensic Club critically analyzes forensic science portrayals in movies, TV shows, and documentaries. Members discuss fact vs fiction, create educational content, and produce their own short films on forensic science topics.', achievements: [{ title: 'Short Film Festival', desc: 'Produced award-winning short films on forensic awareness.' }, { title: 'Myth-Busting Series', desc: 'Created a popular social media series busting forensic myths from movies.' }], projects: [{ title: 'Documentary Production', desc: 'Producing a documentary on real-world forensic case studies.', tag: 'Active' }, { title: 'Film Analysis Blog', desc: 'Running a blog analyzing forensic accuracy in popular media.', tag: 'Active' }], leads: [{ name: 'Dr. Prateek Singh', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'clue-craft', departmentId: 'forensic', name: 'Clue Craft Club', advisor: 'Dr. Prateek Singh', icon: 'fas fa-puzzle-piece', color: '#e74c3c', bgColor: '#fdedec', shortDesc: 'Solving mysteries through logical reasoning and forensic puzzles.', about: 'Clue Craft Club sharpens logical thinking and deductive reasoning through forensic puzzles, mystery-solving challenges, and escape room experiences. Members develop critical thinking skills essential for forensic investigation through gamified learning.', achievements: [{ title: 'Mystery Night Event', desc: 'Organized campus-wide mystery solving events with 200+ participants.' }, { title: 'Escape Room Design', desc: 'Designed and built forensic-themed escape rooms.' }], projects: [{ title: 'Forensic Puzzle App', desc: 'Developing a mobile app with forensic logic puzzles.', tag: 'Research' }, { title: 'Detective Workshop', desc: 'Workshops teaching deductive reasoning and observation skills.', tag: 'Active' }], leads: [{ name: 'Dr. Prateek Singh', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'google-club', departmentId: 'cse', name: 'Google Club', advisor: 'Dr. Ajay Kumar', icon: 'fab fa-google', color: '#4285f4', bgColor: '#e8f0fe', shortDesc: 'Google technologies, Android development, and cloud computing.', about: 'The Google Club is the go-to community for students passionate about Google technologies. From Android app development and Firebase to Google Cloud Platform and TensorFlow, members build projects using Google\'s ecosystem and prepare for Google certifications.', achievements: [{ title: 'Google Solution Challenge', desc: 'Participated in Google Solution Challenge with impactful projects.' }, { title: 'Android Dev Workshop', desc: 'Trained 200+ students in Android app development.' }], projects: [{ title: 'Campus Android App', desc: 'Building an all-in-one campus companion Android application.', tag: 'Active' }, { title: 'Cloud Study Group', desc: 'Preparing members for Google Cloud certification exams.', tag: 'Active' }], leads: [{ name: 'Dr. Ajay Kumar', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'robox-club', departmentId: 'cse', name: 'RoboX Club', advisor: 'Dr. Ratnesh Shukla', icon: 'fas fa-robot', color: '#1abc9c', bgColor: '#e8f8f5', shortDesc: 'Robotics, automation, IoT, and hands-on hardware projects.', about: 'RoboX Club combines computer science with robotics and hardware. Members build robots, work with Arduino, Raspberry Pi, IoT sensors, and explore the intersection of software and hardware through exciting practical projects.', achievements: [{ title: 'Robotics Competition Winner', desc: 'Won prizes at state-level robotics competitions.' }, { title: 'IoT Smart Campus', desc: 'Deployed IoT sensors for campus environment monitoring.' }], projects: [{ title: 'Line Follower Bot', desc: 'Building an advanced PID-controlled line following robot.', tag: 'Active' }, { title: 'Smart Home Prototype', desc: 'IoT-based smart home automation system.', tag: 'Active' }], leads: [{ name: 'Dr. Ratnesh Shukla', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'ai-ignite', departmentId: 'cse', name: 'AI Ignite Club', advisor: 'Dr. Ankita Srivastav', icon: 'fas fa-brain', color: '#9b59b6', bgColor: '#f5eef8', shortDesc: 'Artificial intelligence, machine learning, and data science.', about: 'AI Ignite Club fuels the passion for artificial intelligence and machine learning. Members explore deep learning, NLP, computer vision, and data science through workshops, Kaggle competitions, research projects, and industry-mentored sessions.', achievements: [{ title: 'ML Hackathon Winners', desc: 'Won inter-college ML hackathon with an NLP project.' }, { title: 'AI Workshop Series', desc: 'Conducted a 10-part AI/ML workshop series for 300+ students.' }], projects: [{ title: 'Sentiment Analyzer', desc: 'NLP-based social media sentiment analysis tool.', tag: 'Active' }, { title: 'Image Classifier', desc: 'CNN-based image classification for campus plant species.', tag: 'Research' }], leads: [{ name: 'Dr. Ankita Srivastav', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'codex-club', departmentId: 'cse', name: 'CodeX Club', advisor: 'Dr. Amit Mishra', icon: 'fas fa-code', color: '#2ecc71', bgColor: '#eafaf1', shortDesc: 'Competitive programming, DSA, and software development.', about: 'CodeX Club is the coding powerhouse. From competitive programming and data structures to full-stack development and open-source contributions, the club builds strong problem-solving foundations through regular contests, coding bootcamps, and collaborative projects.', achievements: [{ title: 'Coding Competition Champions', desc: 'Won multiple inter-college coding competitions.' }, { title: 'Open Source Contributions', desc: 'Members contributed to notable open-source projects.' }], projects: [{ title: 'Online Judge Platform', desc: 'Building a custom competitive programming judge.', tag: 'Active' }, { title: 'DSA Bootcamp', desc: 'Structured bootcamp covering all DSA topics.', tag: 'Active' }], leads: [{ name: 'Dr. Amit Mishra', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'tech-shield', departmentId: 'cse', name: 'Tech Shield', advisor: 'Proposed', icon: 'fas fa-shield-alt', color: '#e74c3c', bgColor: '#fdedec', shortDesc: 'Cybersecurity, ethical hacking, and digital safety.', about: 'Tech Shield is a proposed club focusing on cybersecurity and ethical hacking. Once operational, it will provide training in network security, penetration testing, CTF competitions, and digital forensics to prepare students for the growing cybersecurity landscape.', achievements: [], projects: [{ title: 'CTF Platform', desc: 'Planning to build an in-house CTF challenge platform.', tag: 'Proposed' }], leads: [{ name: 'To be announced', role: 'Faculty Advisor (Proposed)', email: '#', linkedin: '#' }], status: 'proposed' },
    { id: 'bit-brain', departmentId: 'cse', name: 'Bit Brain', advisor: 'Proposed', icon: 'fas fa-microchip', color: '#3498db', bgColor: '#ebf5fb', shortDesc: 'Hardware programming, microcontrollers, and embedded systems.', about: 'Bit Brain is a proposed club dedicated to low-level programming, microcontroller development, and embedded systems. The club will bridge the gap between hardware and software through projects involving FPGA, ARM, and system-level programming.', achievements: [], projects: [{ title: 'Embedded Systems Lab', desc: 'Planning to set up a dedicated embedded systems workspace.', tag: 'Proposed' }], leads: [{ name: 'To be announced', role: 'Faculty Advisor (Proposed)', email: '#', linkedin: '#' }], status: 'proposed' },
    { id: 'dev-hive', departmentId: 'cse', name: 'Dev Hive', advisor: 'Proposed', icon: 'fas fa-laptop-code', color: '#e67e22', bgColor: '#fef5e7', shortDesc: 'Full-stack development, web technologies, and app creation.', about: 'Dev Hive is a proposed club for aspiring developers to collaborate on real-world web and mobile application projects. The club will focus on modern development frameworks, DevOps practices, and building products from ideation to deployment.', achievements: [], projects: [{ title: 'Dev Community Portal', desc: 'Planning to build a developer community platform.', tag: 'Proposed' }], leads: [{ name: 'To be announced', role: 'Faculty Advisor (Proposed)', email: '#', linkedin: '#' }], status: 'proposed' },
    { id: 'hack-with-india', departmentId: 'computing', name: 'Hack with India', advisor: 'Mr. Nizamaudin', icon: 'fas fa-flag', color: '#ff6b35', bgColor: '#fff0e8', shortDesc: 'Hackathons, innovation challenges, and national tech competitions.', about: 'Hack with India is a dynamic club that prepares students for national-level hackathons, innovation challenges, and startup competitions. Members form teams, ideate solutions for real-world problems, and compete at prestigious events across India.', achievements: [{ title: 'Smart India Hackathon', desc: 'Teams participated in Smart India Hackathon multiple years.' }, { title: 'Hackathon Organizer', desc: 'Organized intra-college hackathons with 150+ participants.' }], projects: [{ title: 'Hackathon Prep Program', desc: 'Structured preparation program for national hackathons.', tag: 'Active' }, { title: 'Problem Statement Bank', desc: 'Curated bank of real-world problem statements for practice.', tag: 'Active' }], leads: [{ name: 'Mr. Nizamaudin', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'coding-startup', departmentId: 'computing', name: 'Coding & Startup Innovation Club', advisor: 'Mr. Nizamaudin', icon: 'fas fa-rocket', color: '#e74c3c', bgColor: '#fdedec', shortDesc: 'Coding skills with entrepreneurial mindset and startup culture.', about: 'This club merges technical coding skills with entrepreneurial thinking. Members learn to code, build MVPs, develop business plans, and pitch startup ideas. The club fosters a culture of innovation where technical skills meet business acumen.', achievements: [{ title: 'Startup Weekend', desc: 'Organized a 54-hour startup weekend event.' }, { title: 'Pitch Competition', desc: 'Members won prizes at regional startup pitch competitions.' }], projects: [{ title: 'Startup Incubation', desc: 'Mentoring student startup ideas from concept to MVP.', tag: 'Active' }, { title: 'Coding Bootcamp', desc: 'Intensive coding bootcamps for beginners.', tag: 'Active' }], leads: [{ name: 'Mr. Nizamaudin', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'tech-verse', departmentId: 'computing', name: 'Tech Verse', advisor: 'Mr. Nizamaudin', icon: 'fas fa-globe', color: '#3498db', bgColor: '#ebf5fb', shortDesc: 'Exploring emerging technologies and digital transformation.', about: 'Tech Verse explores the ever-evolving landscape of emerging technologies — from blockchain and Web3 to AR/VR and quantum computing. The club keeps students at the cutting edge of technology trends through seminars, demos, and hands-on sessions.', achievements: [{ title: 'Tech Talk Series', desc: 'Hosted 20+ tech talks featuring industry professionals.' }, { title: 'Web3 Workshop', desc: 'Conducted workshops on blockchain and decentralized applications.' }], projects: [{ title: 'Tech Newsletter', desc: 'Weekly newsletter covering latest tech trends and breakthroughs.', tag: 'Active' }, { title: 'AR Campus Tour', desc: 'Building an augmented reality campus tour experience.', tag: 'Research' }], leads: [{ name: 'Mr. Nizamaudin', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'smart-tech', departmentId: 'computing', name: 'Smart Tech', advisor: 'Mr. Nizamaudin', icon: 'fas fa-cog', color: '#16a085', bgColor: '#e8f8f5', shortDesc: 'Smart devices, automation, and intelligent systems.', about: 'Smart Tech club focuses on building intelligent systems and smart devices. From home automation and wearables to smart agriculture and intelligent transportation, members design and build practical solutions using IoT, sensors, and AI.', achievements: [{ title: 'Smart Campus Project', desc: 'Implemented smart lighting and monitoring systems on campus.' }, { title: 'Innovation Fair', desc: 'Showcased 10+ smart device prototypes at the innovation fair.' }], projects: [{ title: 'Smart Attendance', desc: 'Building a smart attendance system using face recognition.', tag: 'Active' }, { title: 'Automated Irrigation', desc: 'IoT-based automated plant irrigation system.', tag: 'Active' }], leads: [{ name: 'Mr. Nizamaudin', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'finance-investment', departmentId: 'management', name: 'Finance and Investment Club', advisor: 'Dr. Shradha Verma', icon: 'fas fa-chart-line', color: '#27ae60', bgColor: '#e8f8f0', shortDesc: 'Financial literacy, investment strategies, and market analysis.', about: 'The Finance and Investment Club demystifies the world of finance. Members learn about stock markets, investment strategies, financial modeling, personal finance, and participate in virtual trading competitions and case study analyses.', achievements: [{ title: 'Virtual Trading Competition', desc: 'Organized campus-wide virtual stock trading competitions.' }, { title: 'Finance Literacy Week', desc: 'Conducted financial literacy programs reaching 400+ students.' }], projects: [{ title: 'Investment Portfolio Tracker', desc: 'Building a student investment portfolio tracking dashboard.', tag: 'Active' }, { title: 'Market Analysis Reports', desc: 'Publishing weekly market analysis and insights reports.', tag: 'Active' }], leads: [{ name: 'Dr. Shradha Verma', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'hr-leadership', departmentId: 'management', name: 'HR & Leadership Club', advisor: 'Dr. Dipti Sharma', icon: 'fas fa-users', color: '#e67e22', bgColor: '#fef5e7', shortDesc: 'Leadership development, HR practices, and people management.', about: 'The HR & Leadership Club develops future leaders and HR professionals. Through leadership workshops, personality development sessions, group discussions, and case studies, members build essential soft skills and understanding of human resource management.', achievements: [{ title: 'Leadership Summit', desc: 'Organized an annual leadership summit with industry speakers.' }, { title: 'Mock Interview Drive', desc: 'Conducted mock interviews helping 200+ students prepare for placements.' }], projects: [{ title: 'Peer Mentoring Program', desc: 'Running a structured peer mentoring program for juniors.', tag: 'Active' }, { title: 'Leadership Podcast', desc: 'Producing a podcast featuring leaders from various industries.', tag: 'Active' }], leads: [{ name: 'Dr. Dipti Sharma', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'marketing-club', departmentId: 'management', name: 'Marketing Club', advisor: 'Dr. Vivek Verma', icon: 'fas fa-bullhorn', color: '#e74c3c', bgColor: '#fdedec', shortDesc: 'Digital marketing, branding, and consumer behavior analysis.', about: 'The Marketing Club explores the dynamic world of marketing — from traditional strategies to cutting-edge digital marketing. Members learn about branding, consumer behavior, social media marketing, content creation, and analytics through live projects and campaigns.', achievements: [{ title: 'Brand Campaign Challenge', desc: 'Won inter-college brand strategy competition.' }, { title: 'Social Media Growth', desc: 'Managed campus event marketing reaching 10,000+ audience.' }], projects: [{ title: 'Campus Branding', desc: 'Developing brand identity and marketing strategy for campus events.', tag: 'Active' }, { title: 'Market Research', desc: 'Conducting consumer behavior research studies.', tag: 'Active' }], leads: [{ name: 'Dr. Vivek Verma', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'esg-entrepreneurship', departmentId: 'management', name: 'ESG & Entrepreneurship Club', advisor: 'Dr. U.S. Yadav', icon: 'fas fa-lightbulb', color: '#f39c12', bgColor: '#fef9e7', shortDesc: 'Sustainability, social impact, and entrepreneurial ventures.', about: 'The ESG & Entrepreneurship Club combines environmental, social, and governance (ESG) principles with entrepreneurial spirit. Members explore sustainable business models, social entrepreneurship, impact investing, and responsible business practices.', achievements: [{ title: 'Sustainability Summit', desc: 'Organized a summit on ESG practices in modern business.' }, { title: 'Startup Mentorship', desc: 'Mentored 10+ student startup ideas focused on sustainability.' }], projects: [{ title: 'ESG Case Studies', desc: 'Analyzing ESG practices of leading Indian companies.', tag: 'Active' }, { title: 'Social Venture Lab', desc: 'Incubating student ventures with social impact focus.', tag: 'Active' }], leads: [{ name: 'Dr. U.S. Yadav', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'automation-robotics', departmentId: 'engineering', name: 'Automation & Robotics Club', advisor: 'Dr. Vineet Dubey', icon: 'fas fa-cogs', color: '#2980b9', bgColor: '#ebf5fb', shortDesc: 'Industrial automation, robotics, and control systems.', about: 'The Automation & Robotics Club explores industrial automation, PLC programming, robotic systems, and control engineering. Members design and build automated systems, robotic arms, and autonomous machines for various applications.', achievements: [{ title: 'Robotics Expo', desc: 'Showcased 8 functional robots at the annual technology expo.' }, { title: 'Automation Challenge', desc: 'Won prizes at the national automation design challenge.' }], projects: [{ title: 'Robotic Arm', desc: 'Building a 6-DOF robotic arm with computer vision.', tag: 'Active' }, { title: 'PLC Automation Lab', desc: 'Setting up a PLC programming and automation lab.', tag: 'Active' }], leads: [{ name: 'Dr. Vineet Dubey', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'circutronix', departmentId: 'engineering', name: 'Circutronix Club', advisor: 'Dr. Neelesh Gupta', icon: 'fas fa-bolt', color: '#e67e22', bgColor: '#fef5e7', shortDesc: 'Circuit design, electronics, and electrical engineering projects.', about: 'Circutronix Club is the hub for circuit enthusiasts. From analog and digital circuit design to PCB fabrication and power electronics, members dive deep into electrical and electronics engineering through hands-on projects and competitions.', achievements: [{ title: 'Circuit Design Competition', desc: 'Won prizes at national circuit design competitions.' }, { title: 'PCB Workshop', desc: 'Conducted PCB design and fabrication workshops for 100+ students.' }], projects: [{ title: 'Custom PCB Projects', desc: 'Designing and fabricating custom PCBs for various applications.', tag: 'Active' }, { title: 'Power Supply Design', desc: 'Building a multi-output variable power supply unit.', tag: 'Active' }], leads: [{ name: 'Dr. Neelesh Gupta', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'cecs', departmentId: 'engineering', name: 'CECS', advisor: 'Dr. Aishvarya Narain', icon: 'fas fa-building', color: '#34495e', bgColor: '#ebedef', shortDesc: 'Civil engineering, construction, and structural design.', about: 'CECS (Civil Engineering & Construction Society) focuses on civil engineering principles, structural design, construction management, and sustainable infrastructure. Members engage in model building, site visits, and structural analysis projects.', achievements: [{ title: 'Bridge Design Competition', desc: 'Won the inter-college model bridge design competition.' }, { title: 'Site Visit Program', desc: 'Organized 15+ industry site visits for practical learning.' }], projects: [{ title: 'Sustainable Housing Model', desc: 'Designing affordable and sustainable housing prototypes.', tag: 'Active' }, { title: 'Structural Analysis Tool', desc: 'Developing a simplified structural analysis calculator.', tag: 'Research' }], leads: [{ name: 'Dr. Aishvarya Narain', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'bioverse', departmentId: 'biotech-btech', name: 'Bioverse', advisor: 'Dr. Anveshika Manoj', icon: 'fas fa-atom', color: '#16a085', bgColor: '#e8f8f5', shortDesc: 'Biotechnology research, bioinformatics, and bio-engineering.', about: 'Bioverse is the BTech biotechnology club that explores cutting-edge biotech research, bioinformatics, genetic engineering, and bio-engineering. Members work on interdisciplinary projects combining biology with engineering and computational methods.', achievements: [{ title: 'Biotech Innovation Award', desc: 'Won best project at the national biotech innovation competition.' }, { title: 'Research Symposium', desc: 'Organized an inter-college biotech research symposium.' }], projects: [{ title: 'Bioinformatics Pipeline', desc: 'Building automated bioinformatics data analysis pipelines.', tag: 'Active' }, { title: 'Biosensor Development', desc: 'Developing low-cost biosensors for environmental monitoring.', tag: 'Research' }], leads: [{ name: 'Dr. Anveshika Manoj', role: 'Faculty Advisor', email: '#', linkedin: '#' }] },
    { id: 'data-sphere', departmentId: 'applied-science', name: 'Data Sphere', advisor: 'Dr. Shartish Singh Mekale', icon: 'fas fa-database', color: '#f39c12', bgColor: '#fef9e7', shortDesc: 'Data analytics, statistical modeling, and applied mathematics.', about: 'Data Sphere is where data meets science. The club focuses on data analytics, statistical modeling, mathematical computation, and data visualization. Members work with real datasets, learn analytical tools, and apply mathematical concepts to solve real-world problems.', achievements: [{ title: 'Data Analytics Competition', desc: 'Won prizes at national data analytics challenge.' }, { title: 'Analytics Workshop', desc: 'Conducted workshops on Python for data analysis and R programming.' }], projects: [{ title: 'Campus Data Dashboard', desc: 'Building a data visualization dashboard for campus metrics.', tag: 'Active' }, { title: 'Predictive Modeling', desc: 'Statistical modeling for academic performance prediction.', tag: 'Research' }], leads: [{ name: 'Dr. Shartish Singh Mekale', role: 'Faculty Advisor', email: '#', linkedin: '#' }] }
];

const ACHIEVEMENTS_DATA = [
    { date: 'March 2025', title: 'National Moot Court — Finalist', desc: 'Moot Court Society reached the finals at a national-level moot court competition.', icon: 'fas fa-gavel' },
    { date: 'February 2025', title: 'Smart India Hackathon Participation', desc: 'Teams from Hack with India and CodeX Club represented at SIH 2025.', icon: 'fas fa-laptop-code' },
    { date: 'January 2025', title: 'AI/ML Hackathon — 1st Place', desc: 'AI Ignite Club won the inter-college machine learning hackathon.', icon: 'fas fa-brain' },
    { date: 'December 2024', title: 'Robotics Expo — Best Innovation', desc: 'Automation & Robotics Club won best innovation at the annual tech expo.', icon: 'fas fa-robot' },
    { date: 'November 2024', title: 'State Coding Competition — Winners', desc: 'CodeX Club members secured top positions at the state coding championship.', icon: 'fas fa-code' },
    { date: 'October 2024', title: 'Legal Aid Camp — 500+ Beneficiaries', desc: 'Legal Aid Cell conducted community camps benefiting 500+ individuals.', icon: 'fas fa-balance-scale' },
    { date: 'September 2024', title: 'Forensic Science Workshop — National Level', desc: 'School of Forensic Science hosted a national-level forensic workshop.', icon: 'fas fa-fingerprint' },
    { date: 'August 2024', title: 'Biotech Innovation Award', desc: 'Bio Innovation Club won best project at the national biotech competition.', icon: 'fas fa-dna' },
    { date: 'July 2024', title: 'Finance Literacy Week — 400+ Participants', desc: 'Finance and Investment Club conducted a week-long financial literacy event.', icon: 'fas fa-chart-line' },
    { date: 'June 2024', title: 'Circuit Design National Competition', desc: 'Circutronix Club won prizes at the national circuit design competition.', icon: 'fas fa-bolt' }
];

const EVENTS_DATA = [
    { title: 'SciFi Hackathon 2025', date: '2025-04-15', day: '15', month: 'Apr', time: '9:00 AM', venue: 'Innovation Lab', desc: 'A 36-hour hackathon focused on building solutions for real-world problems. Open to all students.', type: 'upcoming' },
    { title: 'AI/ML Workshop Series', date: '2025-04-01', day: '01', month: 'Apr', time: '3:00 PM', venue: 'CSE Lab', desc: 'A 5-part workshop series covering ML fundamentals to advanced deep learning by AI Ignite Club.', type: 'upcoming' },
    { title: 'Open House 2025', date: '2025-04-20', day: '20', month: 'Apr', time: '10:00 AM', venue: 'Main Campus', desc: 'Annual Open House showcasing live project demonstrations from all 33 clubs.', type: 'upcoming' },
    { title: 'Moot Court Competition', date: '2025-03-28', day: '28', month: 'Mar', time: '10:00 AM', venue: 'Auditorium', desc: 'Inter-college moot court competition organized by the Moot Court Society.', type: 'upcoming' },
    { title: 'Robotics Workshop', date: '2025-03-22', day: '22', month: 'Mar', time: '2:00 PM', venue: 'Engineering Lab', desc: 'Hands-on robotics workshop by RoboX Club covering Arduino and sensor integration.', type: 'upcoming' },
    { title: 'PCB Design Workshop', date: '2025-02-15', day: '15', month: 'Feb', time: '4:00 PM', venue: 'Electronics Lab', desc: 'Hands-on PCB design workshop by Circutronix Club covering KiCad and board layout.', type: 'past' },
    { title: 'Legal Awareness Camp', date: '2025-01-20', day: '20', month: 'Jan', time: '9:00 AM', venue: 'Community Center', desc: 'Legal Aid Cell organized a legal awareness camp for the local community.', type: 'past' },
    { title: 'Data Analytics Bootcamp', date: '2024-12-10', day: '10', month: 'Dec', time: '2:00 PM', venue: 'Computer Lab', desc: 'Intensive data analytics bootcamp by Data Sphere covering Python and R.', type: 'past' },
    { title: 'Herbal Medicine Seminar', date: '2024-11-15', day: '15', month: 'Nov', time: '10:00 AM', venue: 'Pharmacy Hall', desc: 'Seminar on evidence-based herbal medicine organized by Herbal Club.', type: 'past' }
];

const MEDIA_DATA = [
    { title: 'SciFi Clubs Inaugurated — 33 Clubs Launch', type: 'press', desc: 'All 33 clubs across 10 departments officially inaugurated with faculty advisors.', date: 'March 2025', icon: 'fas fa-newspaper' },
    { title: 'AI Ignite Workshop — Full Highlights', type: 'video', desc: 'Watch highlights from the AI/ML workshop series conducted by AI Ignite Club.', date: 'February 2025', icon: 'fas fa-play-circle' },
    { title: 'Life at SciFi: Student Stories', type: 'blog', desc: 'Students share their experiences and growth through SciFi clubs.', date: 'January 2025', icon: 'fas fa-blog' },
    { title: 'Moot Court Competition Coverage', type: 'press', desc: 'Coverage of the inter-college moot court competition by Legal Studies.', date: 'December 2024', icon: 'fas fa-newspaper' },
    { title: 'Robotics Expo Timelapse', type: 'video', desc: 'Watch the amazing robot builds showcased at the annual Robotics Expo.', date: 'November 2024', icon: 'fas fa-play-circle' },
    { title: 'Why Join a Club? Faculty Perspectives', type: 'blog', desc: 'Faculty advisors share why being part of a club transforms your education.', date: 'October 2024', icon: 'fas fa-blog' }
];

const ALUMNI_DATA = [
    { name: 'Alumni Member 1', club: 'CodeX Club', year: '2025', role: 'Software Engineer', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 2', club: 'AI Ignite Club', year: '2025', role: 'Data Scientist', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 3', club: 'Google Club', year: '2024', role: 'Android Developer', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 4', club: 'Moot Court Society', year: '2024', role: 'Advocate', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 5', club: 'RoboX Club', year: '2024', role: 'Robotics Engineer', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 6', club: 'Finance and Investment Club', year: '2023', role: 'Financial Analyst', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 7', club: 'Crime Scene & Investigator', year: '2023', role: 'Forensic Analyst', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 8', club: 'Bio Innovation Club', year: '2023', role: 'Research Scientist', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 9', club: 'Automation & Robotics Club', year: '2022', role: 'Automation Engineer', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 10', club: 'Herbal Club', year: '2022', role: 'Pharmacist', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 11', club: 'Data Sphere', year: '2022', role: 'Data Analyst', icon: 'fas fa-user-graduate' },
    { name: 'Alumni Member 12', club: 'Hack with India', year: '2021', role: 'Startup Founder', icon: 'fas fa-user-graduate' }
];
